# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3556f75c31f32b18a6c581b64982e46a88b818dff99be0ca641ebacdc93298d88fc4df9b86693abb216df481557b1e69ebcab9d1d52260b59e86160193391bbb

test:
  secret_key_base: 4b7060b34126e237f8d12e2419a5f20a8106f884a62096b79886b833efcebc638ccebfea14765997d8b6c01ec5965c037c3890c42421c1332f7762904b16333d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
